cluster.name: "docker-cluster"
network.host: 0.0.0.0

xpack.security.http.ssl.enabled: 'false'
xpack.security.transport.ssl.enabled: 'false'

node.roles:
  - master
  - data
  - ingest

cluster.routing.allocation.same_shard.host: 'true'
cluster.routing.allocation.disk.threshold_enabled: 'true'
cluster.routing.allocation.disk.watermark.low: 50%
cluster.routing.allocation.disk.watermark.high: 70%
xpack.security.enabled: 'false'

# Create a new cluster with the current node only
# Additional nodes can still join the cluster later
cluster.initial_master_nodes: ["e47736b7ad5b"]
