---

- hosts: localhost

  vars:
    persist_path_prefix: "{{ lookup('env', 'HOME') }}"
    dir_owner: "{{ lookup('env', 'USER') }}"
    dir_group: "{{ dir_owner }}"

  tasks:
  - name: Set architecture specific variables
    set_fact:
      arch: "{{ 'arm64' if ansible_facts.architecture == 'aarch64' or ansible_facts.architecture == 'arm64' else 'amd64' }}"

  - name: Set user group variable when MacOS
    set_fact:
      dir_group: "staff"
    when: ansible_os_family == "Darwin"

  - name: Create es01 data directory
    ansible.builtin.file:
      path: "{{ persist_path_prefix }}/persist/es01/data"
      state: directory
      owner: "{{ dir_owner }}"
      group: "{{ dir_group }}"
      mode: 0775
      recurse: yes

  - name: Create es01 config directory
    ansible.builtin.file:
      path: "{{ persist_path_prefix }}/persist/es01/config"
      state: directory
      owner: "{{ dir_owner }}"
      group: "{{ dir_group }}"
      mode: 0775
      recurse: yes

  - name: Copy es01 config files
    ansible.builtin.copy:
      src: persist/es01/config/
      dest: "{{ persist_path_prefix }}/persist/es01/config/"
      owner: "{{ dir_owner }}"
      group: "{{ dir_group }}"
      mode: '0644'
      backup: yes

  - name: Create cerebro conf directory
    ansible.builtin.file:
      path: "{{ persist_path_prefix }}/persist/cerebro/conf"
      state: directory
      owner: "{{ dir_owner }}"
      group: "{{ dir_group }}"
      mode: 0775
      recurse: yes

  - name: Copy cerebro files
    ansible.builtin.copy:
      src: persist/cerebro/conf/
      dest: "{{ persist_path_prefix }}/persist/cerebro/conf/"
      owner: "{{ dir_owner }}"
      group: "{{ dir_group }}"
      mode: '0644'
      backup: yes

  - name: Create kibana conf directory
    ansible.builtin.file:
      path: "{{ persist_path_prefix }}/persist/kibana/config"
      state: directory
      owner: "{{ dir_owner }}"
      group: "{{ dir_group }}"
      mode: 0775
      recurse: yes

  - name: Copy kibana config files
    ansible.builtin.copy:
      src: persist/kibana/config/
      dest: "{{ persist_path_prefix }}/persist/kibana/config/"
      owner: "{{ dir_owner }}"
      group: "{{ dir_group }}"
      mode: '0644'
      backup: yes

  - name: Copy docker-compose yml
    template:
      src: ./docker-compose.j2
      dest: ./docker/docker-compose.yml

  - name: Run elasticssearch environment on Mac
    shell:
      cmd: "docker-compose -f docker-compose.yml up -d"
      chdir: ./docker/
    when: ansible_facts['os_family'] == "Darwin"

  - name: Run elasticssearch environment on Ubuntu
    become: True
    shell:
      cmd: "docker-compose -f docker-compose.yml up -d"
      chdir: ./docker/
    when: ansible_facts['os_family'] == "Debian"
