---

- hosts: localhost

  tasks:
  - name: Create es01 data directory
    ansible.builtin.file:
      path: /persist/es01/data
      state: directory
      owner: root
      group: root
      mode: 0775
      recurse: yes

  - name: Create es01 config directory
    ansible.builtin.file:
      path: /persist/es01/config
      state: directory
      owner: root
      group: root
      mode: 0775
      recurse: yes

  - name: Create cerebro conf directory
    ansible.builtin.file:
      path: /persist/cerebro/conf
      state: directory
      owner: root
      group: root
      mode: 0775
      recurse: yes

  - name: Copy docker-compose yml
    template:
      src: ./docker-compose.j2
      dest: ./docker/docker-compose.yml

  - name: Run elasticssearch environment
    become: True
    shell:
      cmd: "docker-compose -f docker-compose.yml up -d"
      chdir: ./docker/
